version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports: 
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: securly
   app:
     depends_on: 
       - db
    
     build: 
       context: ./
       dockerfile: dockerfile
     image: securly
     ports:
       - "8000:80"
     restart: always
     volumes:
      - C:\Users\Fritz\Coding\securly\interview\web:/var/www/html
volumes:
  db_data: